#!/bin/bash
set -u

echo -e "Input hostname(e.g. google.co.jp).\nPress [Ctrl+d] when input finished."
while read line
do
  array+=($line)
done

exec /usr/local/bin/deadman <(
for host in ${array[@]}
do
  # A
  As=`host -N 2 -t a ${host} | grep "has address" | awk '{print $4}'`
  if [ "${As}" ]; then
    for A in ${As[@]}; do
      echo "${host} ${A}"
    done
  fi

  # AAAA
  AAAAs=`host -N 2 -t aaaa ${host} | grep "has IPv6 address" | awk '{print $5}'`
  if [ "${AAAAs}" ]; then
    for AAAA in ${AAAAs}; do
      echo "${host} ${AAAA}"
    done
  fi

  # IPv4
  IPv4s=`echo ${host} | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
  if [ "${IPv4s}" ]; then
    for IPv4 in ${IPv4s}; do
      echo "${IPv4} ${IPv4}"
    done
  fi

  # IPv6
  IPv6s=`echo ${host} | grep -E '[0-9A-Fa-f:]*:[0-9A-Fa-f:].*'`
  if [ "${IPv6s}" ]; then
    for IPv6 in ${IPv6s}; do
      echo "${IPv6} ${IPv6}"
    done
  fi
done)
